\documentclass[12pt]{article}    % For submission



%% Package imports %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\usepackage{amsfonts}           % For access to \checkmark.
\usepackage{amsmath}            % For better symbol decorations
\usepackage{authblk}            % For a nice author block
\usepackage{booktabs}           % For nice table rules
\usepackage[official]{eurosym}  % For the euro symbol
\usepackage[figurename=Fig.]{caption} % For changing "Figure" to "Fig." in figure captions
\usepackage{chngcntr}           % To get figure and table numbering correct in the appendices
\usepackage[makeroom]{cancel}   % To show terms go to zero
\usepackage[inline]{enumitem}   % For inline enumeration
\usepackage[letterpaper, left=0.75in, right=0.75in, top=0.75in, bottom=0.75in, footskip=.25in]{geometry} % For better margins.
\usepackage[pagewise]{lineno}   % For line numbers
% \modulolinenumbers[5]
\usepackage{multicol}           % For multi-column layout
\usepackage{multirow}           % For multi-row layout
\usepackage{natbib}
\setlength{\bibsep}{0.0pt}      % To set the separation between entries to 0.
\usepackage{nccmath}            % For the \useshortskip command above equations
\usepackage{parcolumns}         % For multi-column layout
\usepackage{pdflscape}          % For landscape environment \begin{landscape} ... \end{landscape}
\usepackage{setspace}           % For double spacing
\doublespacing
\usepackage{soul}               % For text highlighting
\usepackage[most]{tcolorbox}    % For color highlighting of text
\usepackage{tikz}               % For diagrams
\usetikzlibrary{arrows,positioning}
\usepackage{ulem}               % For strikeout command (\sout)
\usepackage{xcolor}             % For ... colors

\usepackage{hyperref}           % hyperref should be the last package loaded


%% Macros defined by authors %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/macros.tex}


%% Bibliography style %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\bibliographystyle{apa-good.bst}

% Author info
\title{Advancing the necessary foundations \\
              for empirical energy rebound estimates: \\
              A partial equilibrium analysis framework}
\author[1,*]{Matthew Kuperus Heun}
\author[2]{Gregor Semieniuk}
\author[3]{Paul E.\ Brockway}
\affil[1]{Engineering Department, Calvin University, 3201 Burton St. SE, Grand Rapids, MI, 49546}
\affil[2]{Political Economy Research Institute and 
                            Department of Economics,
                            UMass Amherst}
\affil[3]{Sustainability Research Institute, 
                             School of Earth and Environment,
                             University of Leeds}
\affil[*]{\normalfont{Corresponding author: \texttt{mkh2@calvin.edu}}}
\renewcommand\Affilfont{\itshape\small}

\date{} % Kill the date

\singlespace

\begin{document}

\maketitle


%% Abstract %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{abstract}
Widespread implementation of energy efficiency
is a key greenhouse gas emissions mitigation measure, 
but rebound can ``take back''
energy savings.
However, conceptual foundations lag behind empirical estimates of the size of rebound.
We posit that development of solid analytical frameworks for rebound
is hampered by the interdisciplinary nature of the topic, 
involving both economics and energy analysis.
In this paper, we help advance a rigorous analytical framework
that starts at the microeconomics of rebound
and is approachable for both energy analysts and economists. 
We include emplacement, substitution, and income rebound effects and
link them to macro rebound.
Novel graphs show rebound paths through energy, expenditure, and consumption spaces.
Application of the framework provides estimates of total rebound in two case studies: 
upgrades of a car (48\%) and an electric lamp (80\%).
Sensitivities are evaluated, and 
implications for common policies are considered.
\end{abstract}

Keywords: Energy efficiency, Energy rebound, Energy services, Microeconomic rebound, Substitution and income effects, Macroeconomic rebound



<<setup, echo=FALSE, message=FALSE>>=
library(dplyr)
library(magrittr)
library(MKHthemes)
library(ReboundTools)
library(tidyr)
library(xtable)
@

% \linenumbers


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
\label{sec:introduction}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%





The remainder of this paper is structured as follows.
Section~\ref{sec:setup} lays the groundwork for our framework and reviews existing literature.
Section~\ref{sec:framework} describes the comprehensive rebound analysis framework.
Section~\ref{sec:examples} provides two examples: 
energy efficiency upgrades to a car and an electric lamp.
Section~\ref{sec:discussion} discusses the results, and 
Section~\ref{sec:conclusion} concludes.


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Background}
\label{sec:setup}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%++++++++++++++++++++++++++++++
%\subsection{Rebound analysis frameworks}
%\label{sec:rebound_frameworks}
%++++++++++++++++++++++++++++++

Rebound analysis frameworks are used to estimate the magnitude of rebound effects 
and total rebound from an EEU (energy efficiency upgrade).
We use the word ``framework'' to mean 
the basic structure for analysis of a system or concept,
in this case energy rebound.
We define a rebound framework to be a rebound typology
applied to the task of estimating rebound for a particular EEU.
A rebound typology is a description and explication of rebound effects, locations, and scales.
Rebound frameworks are operationalized by a series of equations,
typically ending with a summation equation for
total rebound across all effects, locations, and scales.
For accurate analysis of the size of rebound from a given EEU, 
rebound frameworks should be comprehensive, 
accounting for all rebound effects
in energy, expenditure, and consumption spaces
with a detailed model of consumer responses 
to non-marginal energy efficiency changes.%
\footnote{
  Note that non-marginal (i.e., large) energy efficiency gains are quite common
  but missing from previous rebound analysis frameworks.
  See Section~\ref{sec:non_marginal_changes}.
}

In the subsections that follow, 
rebound frameworks are further elucidated, 
starting with features of rebound typologies and analysis spaces.
Thereafter, characteristics of rebound frameworks are discussed, 
including 
the importance of detailed models of consumer preferences, 
the importance of non-marginal energy service price changes, and 
the need for operationality.


%------------------------------
\subsection{Typologies: effects, locations, scales} 
\label{sec:rebound_typologies}
%------------------------------

Any comprehensive rebound framework should include 
in its typology
emplacement, substitution, income, and macro effects.
For a given EEU, 
it cannot be known \emph{a priori}
which rebound effects will be large and which will be small, 
so all effects should be analyzed.
The emplacement effect of an EEU includes 
%
\begin{enumerate*}[label={(\roman*)}]
	
  \item expected energy savings, assuming no behavioral changes;
  
  \item embodied energy effects, i.e.\ changes across the EEU of the embodied energy rate 
        of the energy conversion device; and 
        
  \item maintenance and disposal effects 
        (changes in the energy implications of 
        these activities caused by the EEU).
    
\end{enumerate*}
%
The substitution effect accounts for behavior changes across the EEU,
typically increased use of the upgraded device and decreased consumption of other goods due to relative price changes,
assuming no change in device owner utility.
The emplacement and substitution effects create net financial savings
which are spent by the device owner 
in the income effect on more of the energy service and 
more other goods and services. 
Finally, the macro effect accounts for %long-run
economic expansion (and subsequent changing energy consumption),
because the EEU is a cost-saving technological change.

Rebound can occur at direct and indirect locations.
Direct rebound involves takeback of expected savings of energy
consumed by the upgraded device.
Indirect rebound arises from increased energy consumption 
in other locations and in other economic sectors
as a result of the EEU.

Rebound scales include microeconomic and macroeconomic.
Rebound at the microeconomic scale arises from the series of adjustments
to the reduction in the implicit price of the energy service. 
A static economy is assumed. 
Microeconomic rebound includes the emplacement, substitution, and income effects.
Rebound at the macroeconomic scale arises from the 
dynamic response of the economy to reach a new stable equilibrium
(between supply and demand for the energy service and other goods)
in response to the EEU.
Macroeconomic rebound involves various short- and long-run effects.

Because a lot is at stake when analyzing energy rebound, 
it is important that rebound analysis frameworks
account for all effects, locations, and scales;
everything is interconnected.
The emplacement effect
frees the device owner's cash to be spent in the income effect,
with energy implications.
The substitution effect describes behavior adjustments that 
provide further net savings to be spent in the income effect, 
again with energy implications.
And greater efficiency gains and 
behavior changes at the microeconomic scale
are likely to lead to larger macroeconomic rebound.
(We note briefly that 
the link between microeconomic and macroeconomic scales 
is largely unexplored territory.
See Section~\ref{sec:macro_effect_main_paper}
for our approach to the macro effect.)


%------------------------------
\subsection{Rebound spaces} 
\label{sec:rebound_spaces}
%------------------------------

A comprehensive rebound framework will enable analyses
in several conceptual ``spaces'' in which changes occur
because of the EEU.
Energy, expenditure, and consumption spaces are all linked together, 
as illustrated by two examples.
%
\begin{enumerate*}[label={(\roman*)}]
	
  \item Net savings from the EEU are determined in the expenditure space.
        Which goods and services are purchased with net savings 
        is determined by consumer preferences and 
        described in the consumption space.
        The energy implications of purchases vary 
        by the types of goods and services purchased
        and is described in the energy space.

  \item The amount of embodied energy in the upgraded device 
        is described in the energy space and
        may be correlated with the cost of device upgrades, 
        which is described in the expenditure space.
        The cost of the upgrade, in turn,
        has implications for what can be consumed, 
        which is described in the consumption space.
    
\end{enumerate*}
%
Tracking changes across all spaces increases understanding 
of causal linkages across rebound effects, locations, and scales
and clarifies terms and concepts across disciplines.


%------------------------------
\subsection{Behavior and preferences} 
\label{sec:consumer_preferences}
%------------------------------

A comprehensive rebound framework will include a detailed description 
of device owner behavior and preferences.
By ``detailed,'' we mean a payoff 
specification that translates energy service price and device purchase 
cost changes into choices, simultaneously 
decomposing into substitution and income effects. 
These two effects allow for nuanced understanding of behavior
for different commodities and payoff specifications.
Decomposition into substitution and income effects 
has become the standard approach to analyzing
direct and indirect rebound locations 
at the microeconomic scale~\citep{greening2000}.

%------------------------------
\subsection{Non-marginal energy service price changes} 
\label{sec:non_marginal_changes}
%------------------------------

A comprehensive rebound analysis framework 
will allow non-marginal energy service price changes,
because EEUs often involve a large percentage increase in energy efficiency.
A good example of non-marginal energy service price change is 
replacing incandescent lamps with Light Emitting Diode (LED) lamps, 
as discussed in Section~\ref{sec:lamp_example}.
For such EEUs, energy efficiency can increase by nearly a factor of 10
and energy service price can decrease similarly.


%------------------------------
\subsection{Operationality} 
\label{sec:operationalizable}
%------------------------------

An operational rebound analysis framework is one that includes
sufficient descriptions of energy rebound 
for all effects, locations, and scales
in all spaces (energy, expenditure, and consumption) to calculate
quantitative estimates of rebound effects with available real-world data.
This is particularly important for microeconomically grounded, consumer-sided
rebound frameworks that involve unobserved utility functions and,
by extension, substitution and income effects.


%++++++++++++++++++++++++++++++



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Methods: development of the comprehensive rebound framework}
\label{sec:framework}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Results: Two applications of the rebound framework}
\label{sec:examples}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%++++++++++++++++++++++++++++++
\subsection{Sensitivity analyses}
\label{sec:sensitivity_analyses}
%++++++++++++++++++++++++++++++

Sensitivity analyses show the effect of 
independently varied parameters on total rebound and rebound components.
In the context of this framework,
sensitivity analyses
can show important trends, tendencies, and relationships
between rebound parameters and rebound magnitudes.
Key rebound parameters include 
post-EEU efficiency ($\amacro{\eta}$),
capital cost ($\amacro{C}_{cap}$),
energy price ($p_E$),
uncompensated price elasticity of energy service demand ($\eqspsUC$), 
and the macro factor ($k$).
Sensitivity analyses must be interpreted carefully,
because rebound parameters are not expected to be 
independent from each other.

In each subsection below, a series of graphs
shows the effects of varying each of these five key rebound parameters
($\amacro{\eta}$, 
$\amacro{C}_{cap}$, 
$p_E$, 
$\eqspsUC$, 
and $k$)
on total energy rebound ($Re_{tot}$) and its components
($Re_{emb}$, $Re_{md}$, $Re_{dsub}$, $Re_{isub}$,
$Re_{dinc}$, $Re_{iinc}$, and $Re_{\macro}$).
In the graphs, 
nominal values for the rebound parameters are shown as points, 
and sensitivity trends are shown as lines. 
A limitation of each sensitivity analysis 
is noted at the end of each subsection.


%------------------------------
\subsubsection{Effect of post-EEU efficiency ($\amacro{\eta}$)} 
\label{sec:effect_of_efficiency}
%------------------------------

<<efficiency_ratios, echo=FALSE>>=
car_efficiency_ratio <- (rebound_results %>% dplyr::filter(Case == "Car") %>% dplyr::select("eta_engr_units_star") / rebound_results %>% dplyr::filter(Case == "Car") %>% dplyr::select("eta_engr_units_orig")) %>% 
  unlist() %>% 
  formatC(digits = 3)

lamp_efficacy_ratio <- (rebound_results %>% dplyr::filter(Case == "Lamp") %>% dplyr::select("eta_engr_units_star") / rebound_results %>% dplyr::filter(Case == "Lamp") %>% dplyr::select("eta_engr_units_orig")) %>% 
  unlist() %>% 
  formatC(digits = 3)
@

Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph} shows that
both the energy takeback rate and expected energy savings ($\Sdot$)
increase with post-EEU efficiency ($\amacro{\eta}$), 
but the relationship is asymptotic.
Each unit increase of fuel economy or lighting efficacy is less effective than
the previous unit increase of fuel economy or lighting efficacy
for saving energy.
At very high levels of fuel economy or lighting efficacy, 
a unit increase leads to almost no additional energy savings.
Thus, we can say there are diminishing returns of fuel economy and lighting efficacy,
leading to saturation of energy savings at very high levels of fuel economy and lighting efficacy.
A simple example illustrates.
A $\bempl{\eta} = 25$ mpg car drives $\bempl{q}_s = 100$ miles 
using $\bempl{E}_s = 4$ gallons of gasoline.
A more-efficient car ($\amacro{\eta} = 30$ mpg) is expected to use
$\aempl{E}_s = 3.33$ gallons to drive the same distance,
a savings of $\Sdot = 0.67$ gallons.
Another 5 mpg boost in efficiency (to $\amacro{\eta} = 35$ mpg)
will use $\aempl{E}_s = 2.86$ gal to drive 100 miles, 
a further expected savings of only $\Sdot = 0.47$ gallons.
Each successive 5 mpg boost in fuel economy 
saves less energy than the previous 5 mpg boost in fuel economy.


<<eta_tilde_takeback_Sdot_sens_graph, echo=FALSE, fig.cap="Expected energy savings rate ($\\Sdot$, solid line) and takeback rate (dashed line) sensitivity to post-EEU efficiency ($\\amacro{\\eta}$). (Note different $x$- and $y$-axis scales.)", fig.width=6, fig.height=4>>=
actual_cases <- rebound_data %>% 
  dplyr::filter(.data[[ReboundTools::eeu_base_params$case]] %in% c("Car", "Lamp"))

eta_sens_params = list(Car = list(eta_engr_units_star = seq(35, 50, by = 0.5)), 
                       Lamp = list(eta_engr_units_star = seq(70000, 90000, by = 5000)))

eta_sens_data <- ReboundTools::parametric_analysis(original_cases = actual_cases,
                                                   parameterization = eta_sens_params) %>%
  dplyr::mutate(
    takeback = .data[[ReboundTools::rebound_terms$Re_tot]] * .data[[ReboundTools::star_vars$S_dot_dev]]
  )

# This is a hacky formatter function 
# that formats the x-axis numbers of the graphs.
# The argument x_breaks is the breaks for an axis.
# The function checks to see if the breaks are > 1000 and divides by 1000 in that case.
# This approach works, because lm-hr/kW-hr values are > 1000 for the lamp example
# but the car example has mpg (which are all less than 100).
# So this function divides the Lm-hr/kW-hr values by 1000 while leaving the mpg values unchanged.
eta_tilde_formatter <- function(x_breaks) {
  if (all(x_breaks > 1000)) {
    # To convert Lm-hr/kW-hr to Lm-hr/W-hr.
    return(x_breaks/1000)
  }
  # To leave mpg alone.
  return(x_breaks)
}

sensitivity_graphs(.parametric_data = eta_sens_data,
                   x_var = "eta_engr_units_star", 
                   y_var = c(ReboundTools::star_vars$S_dot_dev, "takeback")) +
  ggplot2::facet_wrap(facets = "Case", scales = "free") +
  ggplot2::scale_x_continuous(labels = eta_tilde_formatter) +
  ggplot2::scale_y_continuous(limits = c(0, NA)) +
  ggplot2::scale_colour_manual(values = c(S_dot_dev = "black", takeback = "black"), guide = "none") + 
  ggplot2::scale_size_manual(values = c(S_dot_dev = 0.5, takeback = 0.5), guide = "none") + 
  ggplot2::scale_linetype_manual(values = c(S_dot_dev = "solid", takeback = "dashed"), guide = "none") +
  ggplot2::labs(x = expression(tilde(eta)*" [mpg (Car) or lm-hr/W-hr (Lamp)]"),
                y = expression("Takeback rate and "*dot(S)[dev]*" [MJ/yr]"),
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() + 
  ggplot2::theme(        
    # Move the facet labels out of the graphs slightly.
    strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2))
  )
@


Saturation can be seen mathematically, too.
Taking the limit as $\amacro{\eta} \rightarrow \infty$ 
in Eq.~(\ref{eq:Sdot}) gives $\Sdot = \rbempl{E}_s$, 
not $\infty$. 
Thus, efficiency saturation must occur.
Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph}
shows that this framework correctly replicates
expected efficiency saturation trends.

Saturation is especially noticeable in the lamp example
compared to the car example,
the difference being that 
the LED lamp is already much more efficient than the incandescent lamp
(\Sexpr{lamp_efficacy_ratio}$\times$),
whereas the hybrid car is only 
\Sexpr{car_efficiency_ratio}$\times$ more efficient than the conventional gasoline car. 
Thus, at $\amacro{\eta} = \Sexpr{efficacy_better}$ lm-hr/W-hr, 
the energy efficient LED
is far closer to efficiency saturation than the hybrid vehicle 
(at $\amacro{\eta} = \Sexpr{mpg_better}$ mpg).
As a result, further increases in the LED lamp's efficiency 
are less effective than further increases in the hybrid car's efficiency.

That said, actual savings is the difference between the expected energy savings line (solid line)
and the takeback line (dashed line) in Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph}.
Because the gap between the lines grows, 
higher efficiency yields greater energy savings,
even after accounting for rebound effects.
But the actual savings are always less than expected savings, due to takeback.

Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph} shows that
expected energy savings ($\Sdot$) increase faster than takeback 
as $\amacro{\eta}$ increases.
Thus, total rebound ($Re_{tot}$, the ratio of 
takeback rate to expected energy savings rate in Eq.~(\ref{eq:Re_takeback})),
decreases as efficiency grows.
The lamp exhibits a relatively smaller rebound decline with efficiency,
because the lamp example is closer to saturation than the car example.

Fig.~\ref{fig:all_Re_terms_eta_graph} shows the variation of all rebound components
with post-EEU efficiency ($\amacro{\eta}$).
In the car and lamp examples, 
direct substitution rebound ($Re_{dsub}$) is the 
rebound component 
most sensitive to changes in post-EEU efficiency ($\amacro{\eta}$).

A limitation of the energy efficiency sensitivity analysis is that 
post-EEU efficiency ($\amacro{\eta}$)
is unlikely to be independent of other factors, 
such as capital cost ($\amacro{C}_{cap}$).

Note that the sensitivity analysis on post-upgrade efficiency 
($\amacro{\eta}$, Fig.~\ref{fig:all_Re_terms_eta_graph})
is the only sensitivity analysis that requires careful explication
of both the numerator and denominator of Eq.~(\ref{eq:Re_takeback}),
as in Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph}, 
because both the numerator and denominator of Eq.~(\ref{eq:Re_takeback})
change when post-upgrade efficiency ($\amacro{\eta}$) changes.
The denominator of Eq.~(\ref{eq:Re_takeback}) doesn't change for
the sensitivity analyses of Figs.~\ref{fig:all_Re_terms_C_cap_graph}--\ref{fig:all_Re_terms_k_graph}.
Thus, for the remaining sensitivity analyses, 
when the rebound percentage increases (decreases), 
the energy takeback rate in the numerator of Eq.~(\ref{eq:Re_takeback})
increases (decreases) proportionally,
and the actual energy savings rate decreases (increases) accordingly.


<<all_Re_terms_eta_graph, echo=FALSE, fig.cap="Sensitivity of rebound components to post-EEU efficiency ($\\amacro{\\eta}$).", fig.width=6, fig.height=4>>=
Re_graph_params <- ReboundTools::sens_graph_params
Re_graph_params[["include_x_axis"]] <- TRUE
Re_graph_params[["use_latex_legend"]] <- TRUE

Re_terms_order <- ReboundTools::rebound_terms[c(ReboundTools::rebound_terms$Re_tot,
                                                ReboundTools::rebound_terms$Re_macro,
                                                ReboundTools::rebound_terms$Re_dinc,
                                                ReboundTools::rebound_terms$Re_iinc,
                                                ReboundTools::rebound_terms$Re_dsub,
                                                ReboundTools::rebound_terms$Re_isub,
                                                ReboundTools::rebound_terms$Re_dempl,
                                                ReboundTools::rebound_terms$Re_emb,
                                                ReboundTools::rebound_terms$Re_md)] %>% 
  unlist()

rebound_terms_graph(rebound_data = actual_cases, parameterization = eta_sens_params, 
                    x_var = "eta_engr_units_tilde", 
                    Re_terms = Re_terms_order,
                    graph_params = Re_graph_params) +
  ggplot2::facet_wrap(facets = "Case", scales = "free_x") + 
  ggplot2::scale_x_continuous(labels = eta_tilde_formatter) +
  ggplot2::labs(x = expression(tilde(eta)*" [mpg (Car) or lm-hr/W-hr (Lamp)]"),
                y = "Rebound terms [-]",
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() + 
  ggplot2::theme(legend.text.align = 0, 
                 # Move the facet labels out of the graphs slightly.
                 strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2)))
@


%------------------------------
\subsubsection{Effect of capital cost ($\amacro{C}_{cap}$)} 
\label{sec:effect_of_capital_cost}
%------------------------------

The sensitivity of energy rebound
to capital cost ($\amacro{C}_{cap}$) is shown
in Fig.~\ref{fig:all_Re_terms_C_cap_graph}.
All other things being equal,
as capital cost of the EEU rises, 
less net savings result from the emplacement effect,
leading to smaller income, macro, and total rebound.
The same effects would be observed
with increasing maintenance and disposal cost rate ($\ramacro{C}_{\md}$).

A limitation of the capital cost sensitivity analysis is that
capital cost ($\amacro{C}_{cap}$) is unlikely to be
independent of $\amacro{\eta}$.
Within a given energy efficiency technology
(e.g., hybrid cars or LED lamps),
greater capital cost ($\amacro{C}_{cap}$) may be associated with
greater service efficiency ($\amacro{\eta}$).
$\amacro{C}_{cap}$ and $\amacro{\eta}$ should probably be varied jointly,
not independently.

<<all_Re_terms_C_cap_graph, echo=FALSE, fig.cap="Sensitivity of rebound components to capital cost ($\\amacro{C}_{cap}$).", fig.width=6, fig.height=4>>=
C_dot_cap_sens_params <- list(Car = list(C_cap_star = seq(30000, 36000, by = 1000)),
                              Lamp = list(C_cap_star = seq(0.5, 10.0, by = 0.1)))

rebound_terms_graph(rebound_data = actual_cases, parameterization = C_dot_cap_sens_params,
                    x_var = "C_cap_star", 
                    Re_terms = Re_terms_order,
                    graph_params = Re_graph_params) +
  ggplot2::scale_x_continuous(breaks = c(1, 2, 4, 6, 8, 10, seq(30000, 36000, by = 2000))) + 
  ggplot2::facet_wrap(facets = "Case", scales = "free_x") +
  ggplot2::labs(x = expression(tilde(C)[cap]*" [$]"),
                y = "Rebound terms [-]",
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() +
  ggplot2::theme(legend.text.align = 0,
                 # Move the facet labels out of the graphs slightly.
                 strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2)))
@


%------------------------------
\subsubsection{Effect of energy price ($p_E$)} 
\label{sec:effect_of_energy_price}
%------------------------------

<<Germany_results, echo=FALSE>>=
# In the calculations, we include same parameters for German energy prices.
# Extract that information here for use in the paragraph below.
Car_Germany_Re_tot <- rebound_results %>% 
  dplyr::filter(Case == "Car - Germany") %>% 
  dplyr::select("Re_tot")
Lamp_Germany_Re_tot <- rebound_results %>% 
  dplyr::filter(Case == "Lamp - Germany") %>% 
  dplyr::select("Re_tot")
@


The effect of energy price on rebound is shown in Fig.~\ref{fig:all_Re_terms_p_E_graph}.
Increasing energy prices lead to larger total rebound ($Re_{tot}$),
because higher energy prices lead to more net savings ($\rasub{N}$)
to be spent by the device owner.
All other things being equal, more net savings leads to 
more spending on other goods and services that demand energy.

Fig.~\ref{fig:all_Re_terms_p_E_graph} also 
shows the effect of energy price ($p_E$)
on all rebound components.
Most rebound components increase with energy price, 
with the car and lamp examples exhibiting different sensitivities. 
Substitution effects ($Re_{dsub}$ and $Re_{isub}$)
are the only rebound components that decrease with energy price ($p_E$).
Substitution effects decrease with energy price, because 
at high energy price, less behavior adjustment is needed to re-equilibrate 
after emplacement of the efficient device.

<<GermanPrices, echo=FALSE>>=
price_data <- tibble::tribble(~Case, ~Country, ~p_E_engr_units,
                              "Car", "DEU", rebound_data %>% 
                                dplyr::filter(Case == "Car - Germany") %>% 
                                magrittr::extract2("p_E_engr_units"),     # $/USgal
                              "Lamp", "DEU", rebound_data %>% 
                                dplyr::filter(Case == "Lamp - Germany") %>% 
                                magrittr::extract2("p_E_engr_units"))     # $/W-hr
@

In Fig.~\ref{fig:all_Re_terms_p_E_graph}, German energy prices%
\footnote{
  For the car example,
  the gasoline price in Germany is taken as 1.42 \euro{}/liter for the average ``super gasoline'' (95 octane) 
  price in 2018~\citep{finanzen}.
  For the lamp example,
  the electricity price in Germany is taken as 0.3 \euro{}/kW-hr for the 2018 price of a household using 3.5~MWh/year,
  an average value for German households~\citep{bundesministerium}.
  Converting currency (at 1 \euro{} = \$1.21) and
  physical units gives 
  \Sexpr{price_data %>% 
           dplyr::filter(Country == "DEU" & Case == "Car") %>% 
           magrittr::extract2("p_E_engr_units")}~\$/US~gallon and 
  \Sexpr{price_data %>% 
           dplyr::filter(Country == "DEU" & Case == "Lamp") %>% 
           magrittr::extract2("p_E_engr_units")}~\$/kW-hr.}
%
are shown as vertical lines,
providing an indication of possible energy price variations.
All other things being equal, 
if U.S.\ residents paid Germany's energy prices,
energy rebound would be 
$\Sexpr{formatC(unlist(Car_Germany_Re_tot * 100), digits = 3)}$\%
for the car example and 
$\Sexpr{formatC(unlist(Lamp_Germany_Re_tot * 100), digits = 3)}$\%
for the lamp example, assuming $k = 1$.

A limitation of the energy price sensitivity analysis arises from the fact that
energy price is not independent of other parameters.
Indeed, other rebound parameters
would change along with energy price
(especially if moving from one country to another),
including capital cost ($\amacro{C}_{cap}$), 
maintenance and disposal expenditure rate ($\ramacro{C}_{\md}$),
energy intensity of the economy ($I_E$), and
energy service consumption rate ($\rbempl{q}_s$).

<<all_Re_terms_p_E_graph, echo=FALSE, fig.cap="Sensitivity of rebound components to energy price ($p_E$). German energy prices denoted by vertical lines.", fig.width=6, fig.height=4>>=
p_E_sens_params <- list(Car = list(p_E_engr_units = seq(1, 8, by = 0.5)),
                        Lamp = list(p_E_engr_units = seq(0.05, 0.4, by = 0.01)))

rebound_terms_graph(rebound_data = actual_cases, parameterization = p_E_sens_params, 
                    x_var = "p_E_engr_units", 
                    Re_terms = Re_terms_order,
                    graph_params = Re_graph_params) +
  ggplot2::geom_vline(data = price_data, 
                      # mapping = ggplot2::aes_string(xintercept = "p_E_engr_units"), 
                      mapping = ggplot2::aes(xintercept = p_E_engr_units), 
                      linewidth = 0.1) +
  ggplot2::scale_y_continuous(breaks = seq(-0.2, 1, by = 0.2)) +
  ggplot2::facet_wrap(facets = "Case", scales = "free_x") + 
  ggplot2::labs(x = expression(p[E]*" [$/gal (Car) or $/kW-hr (Lamp)]"),
                y = "Rebound terms [-]",
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() +
  ggplot2::theme(legend.text.align = 0,
                 # Move the facet labels out of the graphs slightly.
                 strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2)))
@


%------------------------------
\subsubsection{Effect of elasticity ($\eqspsUC$)} 
\label{sec:effect_of_elasticity}
%------------------------------

Fig.~\ref{fig:all_Re_terms_eps_graph} shows the variation of total rebound ($Re_{tot}$)
with the uncompensated price elasticity of energy service demand ($\eqspsUC$).
The effect is exponential, and
total rebound increases with larger negative values of $\eqspsUC$, as expected.
The lamp example also shows stronger exponential variation than the car example.
The main reason that total rebound values 
are different between the two examples
is the larger absolute value of elasticity ($\eqspsUC$) 
for the lamp ($-0.4$) compared to the car ($-0.2$).
Were the car to have the same elasticity as the lamp ($-0.4$), 
total rebound would be approximately the same for both examples ($\sim 50$\%).
Fig.~\ref{fig:all_Re_terms_eps_graph} shows that direct substitution rebound 
($Re_{dsub}$) is the most sensitive rebound component to changes in $\eqspsUC$.
For the lamp example, indirect income rebound ($Re_{iinc}$) also increases
substantially with $\eqspsUC$, 
because net savings increases substantially with $\eqspsUC$. 

A limitation of the elasticity sensitivity study derives from limitations of the 
CES utility model itself, which constrains price elasticity variation
given an elasticity of substitution.
Uneconomic conditions should be avoided.
For example, negative direct substitution rebound ($Re_{dsub} < 0$)
is obtained when $\left| \eqspsUC \right| < \fCs$,
because the elasticity of substitution goes negative ($\sigma < 0$).
(See Eq.~(\ref{eq:sigma}) in Appendix~\ref{sec:utility_and_elasticities}.)
In reality, smaller negative (closer to 0) price elasticity ($\eqspsUC$)
would correlate with a smaller fraction of expenses spent on the energy service ($\fCs$), 
thereby avoiding the uneconomic condition.
However, a univariate sensitivity study cannot capture this effect and is
best used for smaller variations in $\eqspsUC$
about a nominal value.

<<all_Re_terms_eps_graph, echo=FALSE, fig.cap="Sensitivity of rebound components to uncompensated energy service price elasticity of energy demand ($\\eqspsUC$). (Note reversed $x$-axis scale.)", fig.width=6, fig.height=4>>=
eps_sens_params <- list(Car = list(e_qs_ps_UC = seq(-0.7, -0.1, by = 0.01)),
                        Lamp = list(e_qs_ps_UC = seq(-0.7, -0.1, by = 0.01)))

rebound_terms_graph(rebound_data = actual_cases, parameterization = eps_sens_params,
                    x_var = "e_qs_ps_UC", 
                    Re_terms = Re_terms_order,
                    graph_params = Re_graph_params) +
  ggplot2::facet_wrap(facets = "Case", scales = "free_x") +
  ggplot2::scale_x_reverse() +
  ggplot2::labs(x = expression(epsilon[dot(q)[s]*","*p[s]]),
                y = "Rebound terms [-]",
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() +
  ggplot2::theme(legend.text.align = 0,
                 # Move the facet labels out of the graphs slightly.
                 strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2)))
@


%------------------------------
\subsubsection{Effect of macro factor ($k$)} 
\label{sec:effect_of_macro_factor}
%------------------------------

The sensitivity of energy rebound 
to the macro factor ($k$) is shown 
in Fig.~\ref{fig:all_Re_terms_k_graph}.
The macro factor has a linear effect on total rebound ($Re_{tot}$)
through the macro rebound component ($Re_{\macro}$).
All other rebound components are constant when $k$ is varied independently.

A limitation of the macro factor sensitivity analysis is that
the macro factor ($k$) is unlikely to be 
independent of $I_E$, because 
different values of $k$ imply a different macroeconomy.

<<all_Re_terms_k_graph, echo=FALSE, fig.cap="Sensitivity of rebound components to the macro factor ($k$).", fig.width=6, fig.height=4>>=
k_sens_params <- list(Car = list(k = seq(0.5, 3.5, by = 0.5)),
                      Lamp = list(k = seq(0.5, 3.5, by = 0.5)))

rebound_terms_graph(rebound_data = actual_cases, parameterization = k_sens_params,
                    x_var = "k", 
                    Re_terms = Re_terms_order,
                    graph_params = Re_graph_params) +
  ggplot2::scale_y_continuous(breaks = seq(-0.2, 1, by = 0.2)) + 
  ggplot2::facet_wrap(facets = "Case", scales = "free_x") +
  ggplot2::labs(x = expression("k [-]"),
                y = "Rebound terms [-]",
                colour = ggplot2::element_blank(),
                size = ggplot2::element_blank(),
                linetype = ggplot2::element_blank()) +
  MKHthemes::xy_theme() +
  ggplot2::theme(legend.text.align = 0,
                 # Move the facet labels out of the graphs slightly.
                 strip.text.x = ggplot2::element_text(margin = ggplot2::margin(b = 2)))
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Discussion}
\label{sec:discussion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In this section, we revisit and discuss the contributions indicated 
in Section~\ref{sec:introduction}.
Then we show how the framework enables insights
on energy policy, especially policies to encourage energy efficiency. 
Finally, we discuss and calibrate the macro factor ($k$).


%++++++++++++++++++++++++++++++
\subsection{Contributions}
\label{sec:framework_novelties}
%++++++++++++++++++++++++++++++

In Section~\ref{sec:introduction}, 
we claimed four contributions.
Here, we reiterate and discuss each.

First, we believe we have developed 
the first comprehensive rebound analysis framework to include all of
%
\begin{enumerate*}[label={(\roman*)}]
	
  \item capital cost, embodied energy, and maintenance and disposal effects,
  
  \item non-marginal energy service price decreases, and
  
  \item non-marginal energy efficiency increases.
    
\end{enumerate*}
%
The embodied energy and maintenance and disposal effects
are the energy manifestation of the important difference 
between costless technology upgrades and
(costly) mandated efficiency increases \citep{Gillingham:2013aa,Fullerton2020}.
Costly EEUs are not typically 
included in partial equilibrium rebound frameworks \citep{Azevedo2014,Gillingham:2020aa};
most rebound analysis frameworks assume costless upgrade in both financial and energy terms.
One surprising result from including costly upgrades is
that accounting for differential capital cost ($\Delta \raempl{C}_{cap}$)
can \emph{increase} rebound when
the capital cost rate decreases
($\rorig{C}_{cap} > \raempl{C}_{cap}$).
The lamp example of Section~\ref{sec:lamp_example} illustrates this result.
This finding demonstrates that the costless EEU does not provide an upper bound to rebound,
as previously suggested by \citet{Thomas:2013ab}.

The accommodation of non-marginal energy efficiency increases and 
non-marginal energy service price decreases
is made possible by direct calculation of consumption positions 
via the CES utility model of Eqs.~\ref{eq:q_s_solution}--\ref{eq:Re_isub_CES}, 
rather than relying on the approximate utility model and price elasticities. 

The possibility of precisely decomposing microeconomic rebound into 
substitution and income effects in direct and indirect locations
was outlined by \citet{Khazzoom1980}, 
spelled out clearly by \citet{greening2000}, and 
numerically approximated by \citet{Borenstein:2015aa}. 
Yet, authors of previous operational frameworks of microeconomic rebound
typically show only stylized graphs of indifference curves in the consumption space, 
even if they are numerically precise in other respects 
\citep{Thomas:2013aa,Moshiri2017,Li2018}.

The stylized indifference curves of previous frameworks 
lead to the second contribution of this paper, 
namely the first visualizations of rebound effects
in energy, expenditure, and consumption spaces. 
We call these visualizations ``rebound path graphs,'' and
they can be seen in Figs.~\ref{fig:CarEnergyGraph}--\ref{fig:LampConsGraph}. 
Our precisely drawn and quantified rebound path graphs
through energy, expenditure, and consumption spaces
aid comprehension of and intuition about the various rebound effects
for both energy analysts and economists..

Segment \bartilde{} in energy path graphs is the macro effect,
the third contribution.
We have developed the first operational link between 
rebound effects on macroeconomic and microeconomic scales. 
We both operationalize the link and show how it should be applied:
scaling net savings after the substitution effect.
We further draw upon the MPC literature to show how macro effects 
operate via economic expansion over the long term.
This micro-to-macro link can be seen in Eq.~(\ref{eq:Re_macro_def}) and
in Figs.~\ref{fig:ExampleEnergyPathGraph}, \ref{fig:CarEnergyGraph}, and \ref{fig:LampEnergyGraph}.
We make the first calibration of the macro factor ($k$) 
in Section~\ref{sec:calibrating_k} below.

The fourth contribution is tools for calculating
rebound for other EEUs with this framework.
The tools include an Excel workbook and an \texttt{R} package.
See the Leeds University data repository and
the ReboundTools \texttt{R} package~\citep{Heun:2021us}.


%++++++++++++++++++++++++++++++
\subsection{Policy considerations}
\label{sec:policy}
%++++++++++++++++++++++++++++++

We take for granted that it is desirable
to use energy efficiency to reduce energy consumption and CO$_2$ emissions.
For energy efficiency to be as effective as possible
at reducing CO$_2$ emissions,
rebound should be taken into account.
The sensitivity analyses of Section~\ref{sec:sensitivity_analyses}
enable exploration of policy options that are often suggested
to promote energy efficiency and reduce CO$_2$ emissions:
energy efficiency standards, 
rebates or subsidies, and
carbon pricing or energy taxes.
In the subsections below, 
we discuss the rebound implications of each policy option with reference to the sensitivity analyses
of Section~\ref{sec:sensitivity_analyses}.


%------------------------------
\subsubsection{Energy efficiency standards} 
\label{sec:policy:standards}
%------------------------------

Energy efficiency standards mandate minimum efficiency levels for selling 
energy conversion devices into a market.
One example of energy efficiency standards is 
the Corporate Average Fuel Economy (CAFE) standards for U.S.\ cars.

Fig.~\ref{fig:all_Re_terms_eta_graph} shows that rebound falls
as post-upgrade energy efficiency ($\amacro{\eta}$) rises. 
This result is driven mainly by
decreasing direct substitution effect rebound ($Re_{dsub}$)
as efficiency goes up.
Declining $Re_{dsub}$ is driven by declining (i.e., closer to zero)
compensated own price elasticity of energy service demand ($\eqspsC$),
which leads to an equally declining
uncompensated price elasticity of energy service demand ($\eqspsUC$), 
an observable quantity.
(See also Fig.~\ref{fig:all_Re_terms_eps_graph}.)
As a result, raising the minimum efficiency 
required to participate in a market is beneficial
for reducing energy consumption.
Indeed, Fig.~\ref{fig:eta_tilde_takeback_Sdot_sens_graph} shows the gap between 
the expected energy savings rate and the takeback rate grows with post-emplacement efficiency, so
absolute energy savings are expected to increase as efficiency grows, 
at least for the examples in Section~\ref{sec:examples}.
(We note in passing that this change in price elasticity is 
tractable only because the framework accommodates
non-marginal efficiency changes by calculating the new
consumption bundle directly from the CES utility model.)

However, larger efficiency increases can require higher overnight capital investment
within a given technology, 
which hinders adoption of energy-efficient devices.
One measure often employed to boost adoption is 
financial rebates or subsidies, the subject of the next section.


%------------------------------
\subsubsection{Rebates or subsidies} 
\label{sec:policy:rebates_or_subsidies}
%------------------------------

Larger efficiency increases can require higher capital investment 
within a given technology for an EEU.
To encourage market penetration of higher-efficiency devices, 
rebates or subsidies can be offered to device purchasers to incentivize adoption of 
energy-efficient technologies and grow their markets.
(One example of this approach is current subsidies for battery electric vehicles.)
Providing rebates or subsidies
effectively reduces the capital cost ($\amacro{C}_{cap}$) for the purchaser 
of energy-efficient devices.
However, Fig.~\ref{fig:all_Re_terms_C_cap_graph} shows that reducing capital cost 
increases energy rebound, 
mostly due to the income effect
in which more net savings (thanks to the rebate) 
are available to spend on the energy service and other goods.
Thus, policymakers should be aware that rebound will 
reduce the effectiveness of rebates and subsidies
to generate actual energy savings.

That said, a rebate or subsidy could be used as a tool 
to stimulate initial take-up of a new EEU technology.
From a rebound perspective, 
the subsidy-related stimulus should be removed when
cost reductions due to scale effects and learning by doing \citep{Wilson2012} 
take hold, and
the EEU uptake goes mainstream.

A potential downside to rebates and subsidies is inequities:
only those wealthy enough to afford expensive EEUs 
benefit from the subsidies.
To reduce inequities, income-dependent subsidies 
should be implemented.%
\footnote{
  For a discussion of financing difficulties and the requisite size of rebates, see \citet{Fowlie2018}.
}
Moreover, to avoid rebound generated by rebates or subsidies, 
policymakers may choose to implement energy taxes simultaneously,
effectively raising the price of energy, the topic of the next section.


%------------------------------
\subsubsection{Carbon pricing or energy taxes} 
\label{sec:splicy:energy_taxes}
%------------------------------

An energy tax or other penalty on energy consumption, 
preferably limited to fossil energy, 
likely by a price on carbon 
and enacted alongside the EEU,
does two things at the microeconomic scale.
First, a fossil-energy tax raises the effective price of fossil energy ($p_E$) and 
the price of any fossil-energy-powered energy service ($p_s$).
By raising the relative price of the energy service,
substitution effect rebound ($Re_{sub}$) shrinks, 
as shown in Fig.~\ref{fig:all_Re_terms_p_E_graph}. 
Second, a fossil-energy tax raises net financial savings earned 
by the device owner after emplacing the EEU.
The gross savings of the emplacement effect grows with the effective energy price,
driving higher income effect rebound ($Re_{inc}$).
Higher energy prices lead to higher macro rebound ($Re_{macro}$), too, 
again due to increased gross savings from the emplacement effect, 
assuming a constant value for the product of the macro factor
and the energy intensity of the economy ($k I_E$).
Larger income effect and macro effect rebounds overwhelm
the decrease in substitution effect rebound, 
leading to higher overall rebound 
from the effectively higher energy price,
as shown in Fig.~\ref{fig:all_Re_terms_p_E_graph}. This additional
rebound effect moves \citet{VandenBergh2011} to propose a
simultaneous cap on total energy consumption (or CO$_2$ emissions).
But so long as backfire is avoided
(i.e., total rebound remains less than 100\%),
absolute energy savings will still occur, 
though at a lower rate than expected. 

That said, another outcome of carbon pricing or fossil-energy taxes could be 
reduction of the energy intensity of the economy ($I_E$), 
a dynamic effect not captured by the univariate sensitivity study 
of Fig.~\ref{fig:all_Re_terms_p_E_graph}.
The energy intensity of the economy could drop because
at the macroeconomic scale
higher energy prices are likely to induce both 
energy-saving technical change and
structural change toward an overall lower-energy-intensity economy.
To avoid the price penalty, 
consumers might buy other, more-efficient devices or consume substitutes
both for the energy service and in other areas of life,
thereby contributing to reducing $I_E$.
(See \citet{Hart2018} for a related discussion.)
A less-energy-intensive economy could be further encouraged by policymakers 
with complementary policies 
to encourage use of efficient substitutes,
such as public transport.

If carbon pricing or a fossil-energy tax reduces the energy intensity of the economy ($I_E$), 
all rebound terms whose equations include $I_E$ will be affected.
Thus, although the introduction of carbon prices or fossil-energy taxes
can induce higher income-effect rebound and higher macro-effect rebound, 
those increases might be less than predicted 
by the sensitivity study of Fig.~\ref{fig:all_Re_terms_p_E_graph},
due to reduction of the energy intensity of the economy ($I_E$).
And any reduction of $I_E$ due to fossil-energy taxes
will tend to reduce total rebound ($Re_{tot}$),
increasing the likelihood that backfire will be avoided and
absolute energy savings will occur.
Thus, total rebound estimated by this framework
(which assumes static $I_E$)
could provide an upper bound on rebound
for carbon pricing or fossil-energy taxes.

Carbon pricing or fossil-energy taxes are likely to be an effective policy option
to reduce energy consumption, rebound effects, and CO$_2$ emissions.
But the rebound implications of these policies deserve further study,
perhaps building on \citet{Chan2015}
to untangle the web of interconnected dynamic effects
when multiple fuels are involved.
One note of caution:
across-the-board carbon pricing or fossil-energy taxes could raise further equity issues
by limiting the ability of people in low-income groups to purchase energy \citep{Owen2020}. 
To ameliorate inequities, progressive feebates could be implemented.%
\footnote{
  Feebates route energy tax revenues to lower-income EEU purchasers. 
  See \citet{Boyce2018}.
}






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Conclusions}
\label{sec:conclusion}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Competing interests}
\label{sec:competing_interests}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Declarations of interest: none.


\clearpage


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Author contributions}
\label{sec:author_contributions}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{table}[h]
\begin{center}
\begin{tabular}{r c c c}
  \toprule
                              & MKH          & GS           & PEB          \\
  \midrule
  Conceptualization           & \rating{100} & \rating{100} &              \\
  Methodology                 & \rating{100} & \rating{100} & \rating{100} \\
  Software                    & \rating{100} &              &              \\
  Validation                  & \rating{100} &              & \rating{100} \\
  Formal analysis             & \rating{100} & \rating{100} & \rating{100} \\
  Investigation               & \rating{100} & \rating{100} & \rating{100} \\
  Resources                   & \rating{100} &              &              \\
  Data curation               &              &              & \rating{100} \\
  Writing--original draft     & \rating{100} & \rating{100} & \rating{100} \\
  Writing--review \& editing  & \rating{100} & \rating{100} & \rating{100} \\
  Visualization               & \rating{100} & \rating{100} &              \\
  Supervision                 & \rating{100} &              &              \\
  Project administration      & \rating{100} &              &              \\
  Funding acquisition         &              &              &              \\
\bottomrule
\end{tabular}
\label{tab:credit}
\end{center}
\end{table}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Data repository}
\label{sec:data_repository}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Data and calculations are stored at 
Research Data Leeds Repository
(\url{https://doi.org/10.5518/1201}).
An \texttt{R} package for performing all rebound calculations
can be found at \url{https://github.com/MatthewHeun/ReboundTools}.
(See \citet{Heun:2021us}.)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section*{Acknowledgements}
\label{sec:acknowledgements}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%List funding sources in this standard way to facilitate compliance to funder's requirements: Funding: This work was supported by the National Institutes of Health [grant numbers xxxx, yyyy]; the Bill \& Melinda Gates Foundation, Seattle, WA [grant number zzzz]; and the United States Institutes of Peace [grant number aaaa].

%It is not necessary to include detailed descriptions on the program or type of grants and awards. When funding is from a block grant or other resources available toa university, college, or other research institution, submit the name of the institute or organization that provided the funding.

%If no funding has been provided for the research, please include the following sentence: This research did not receive any specific grant from funding agencies  in the public, commercial, or not-for-profit sectors.

Paul Brockway’s time was funded by the UK Research and Innovation (UKRI) 
Council, supported under EPSRC Fellowship award EP/R024254/1.
The authors are grateful for comments from internal reviewers
Becky Haney and Jeremy Van Antwerp (Calvin University); 
Nathan Chan (University of Massachusetts at Amherst); and 
Zeke Marshall (University of Leeds).
The authors benefitted from discussions with 
Daniele Girardi (University of Massachusetts at Amherst) and 
Christopher Blackburn (Bureau of Economic Analysis).
Finally, the authors thank the students of MKH's Fall 2019 
Thermal Systems Design course (ENGR333) at Calvin University
who studied energy rebound for many energy conversion devices
using an early version of this framework.

% No need for this section label, because BibTeX already provides a "References" heading.
% \section*{References}

{
\scriptsize
\bibliography{HSB_refs}
}


\appendix
\counterwithin{figure}{section}
\counterwithin{table}{section}

% Gives a helpful "Appendices" label
\section*{Appendices}

% Labels each appendix as A, B, C, etc. instead of Appendix A, Appendix B, Appendix C, etc.
\renewcommand{\thesection}{\Alph{section}}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Nomenclature}
\label{sec:nomenclature}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/nomenclature.tex}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Mathematical details of rebound path graphs}
\label{sec:graph_details}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/rebound_path_graph_details.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Derivation of comprehensive, consumer-based rebound analysis framework}
\label{sec:derivation}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/derivation.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Utility models and elasticities}
\label{sec:utility_and_elasticities}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<UtilityAppendix, child="pieces/utility_and_elasticities.Rnw">>=
@



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Proof: Income preference equations satisfy the budget constraint}
\label{sec:proof_income_elasticities}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/proof_income_elasticities.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Other goods expenditures and constant $p_o$}
\label{sec:other_goods_expenditures}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\input{pieces/other_goods_expenditures.tex}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{Income and macro effects and relation to the
marginal propensity to consume (MPC)}
\label{sec:income_macro_mpc}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

<<MPCAppendix, child="pieces/mpc.Rnw">>=
@



\end{document}
